### ISSUE TITLE
Error when i create project from template

### ISSUE THREAD

**Issue by Rastopyr** [Rastopyr/mix-newer#1]
Command:
```bash
mix newer -t https://github.com/alco/mix-phoenix-template.git -o session_secret=abc myphoenix
```

Error that i get:
```
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1    
    
    The following arguments were given to IO.chardata_to_string/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 2 out of 2):
    
        def chardata_to_string(string) when is_binary(string)
        def chardata_to_string(list) when is_list(list)
    
    (elixir) lib/io.ex:445: IO.chardata_to_string/1
    (elixir) lib/file.ex:957: File.rm_rf/1
    (elixir) lib/file.ex:1034: File.rm_rf!/1
    (mix) lib/mix/scm/git.ex:87: Mix.SCM.Git.checkout/1
    lib/mix/tasks/newer.ex:60: Mix.Tasks.Newer.fetch_template/2
    lib/mix/tasks/newer.ex:46: Mix.Tasks.Newer.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2

```

**Comment by Rastopyr** [comment]
Ok, as i see that project was last update 3 years ago, but i found the solution of problem :)

In this point, target directory passed as `dest` key.
https://github.com/alco/mix-newer/blob/master/lib/mix/tasks/newer.ex#L60

But in `master` branch of elixir correct key is `checkout`.
https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/scm/git.ex#L86

I can send PR, for fix this!

**Comment by Rastopyr** [comment]
Resolve by `alpha2` release
